action_player:
  enabled: true
  file: /home/zrene/catkin_ws/src/franka_ros/franka_example_controllers/data/orbit_actions.csv 

data_logger:
  output_folder: /home/zrene/logs

policy:
  enabled: false
  file: /home/zrene/isaac_ws/legged_gym/logs/tactile_door_opening/exported/policies/door_opening_latest.onnx
  # file: /home/zrene/isaac_ws/legged_gym/logs/tactile_door_opening/exported/policies/door_opening_latest.onnx

frequency: 50.0 # Hz

observation_buffer:
  type: SimpleStackedBuffer
  params:
    history_length: 0
  
action_managers:
  -
    type: CartesianImpedanceActionHandler
    params: 
      use_gravity_compensation: true
      stiffness: [400, 400, 400, 100, 100, 100]
      damping: [50, 50, 50, 15, 15, 15]
      link_offset: [0.0, 0.0, 0.0107]
  - 
    type: PandaRosGripperActionHandler
    params: null

observation_managers: 
  -
    type: LastActionObserver
    params: 
      action_ids: [0]
